### ISSUE TITLE
Domoticz is going to support HA MQTT Discovery

### ISSUE THREAD

**Issue by waltervl** [moroen/ZWave-MQTT-plugin#22]
Just a warning. See PR4921 on the domoticz github.
If fully functional in Domoticz no need for this plugin anymore as ZWvaJS2MQTT supports HA MQTT Discovery.

**Comment by heggink** [comment]
That would be pretty significant as that would mean that we could ditch BOTH zigbee2mqtt and zwavejs2mqtt plugins.

It may be a while before we are there but this is a great development!

**Comment by candrea77** [comment]
As by zwavejs2mqtt Commits on Oct 4, 2021 : docs: better explain why mqtt discovery isn't a good choice (#1784)

The preferred method of integrating your Z-Wave components with Home Assistant is through the official Home Assistant [Z-Wave JS integration](https://www.home-assistant.io/integrations/zwave_js), this because MQTT Discovery is limited compared to a native integration and Home Assistant updates frequently break it. Based on this I would **NOT RECCOMMEND** using MQTT Discovery, **_I don't plan to keep it maintained in the future._**

If you elect to use MQTT discovery, the following settings will allow ZWavejs2Mqtt to automatically add devices to Home Assistant. In addition to ZWavejs2Mqtt, you must run an MQTT broker to act as the server.

**Comment by gizmocuz** [comment]
You can setup a MQTT broker literly in minutes with docker, but I think both zigbee2mqtt and zwavejs2mqtt are very mature projects that would not stopped I hope ?
Anyways I started the implementation to get a Ikea Air sensor working, but thought to extend it to support a lot more.
Seems to work pretty nicely already ;) Give it a shot

**Comment by waltervl** [comment]
Mqtt autodiscover is implemented in Domoticz.
