### ISSUE TITLE
Change mqqt port

### ISSUE THREAD

**Issue by dbroome1978** [moroen/ZWave-MQTT-plugin#26]
Good afternoon,
I have my broker on port 1884 but there is no place for me to set the port in the plugin.  I tried appending it to the url but that doesn't work (it tried 192.168.1.130:1884:1883

**Comment by heggink** [comment]
Easiest ATM would be for you to edit plugin.py and change the defined port in that file. just search for 1883 and replace with 1884

**Comment by dbroome1978** [comment]
I did that and also updated it in the python-snoop file.  This fixed that but now I have a new error
Error: (FindModule) Domoticz/DomoticzEx modules not found in interpreter.
Looks like that is because I am using the beta version (which is needed for zigbee2mqtt).  I imagine beta support for a volunteer project is pretty unreasonable and - in any case - outside the problem of this ticket

**Comment by heggink** [comment]
That's weird. I am NOT on a beta that includes DomoticzEx. Are you saying that the plugin (using the old framework) does not work on the latest domoticz versions that includes DomoticzEx (which does not have the 256 device limit)? That would be a definite problem since moving from the plugin to the built-in autodiscovery is then an immediate issue..

**Comment by moroen** [comment]
This plugin is more or less "dead in the water", since the new autodiscovery feature build into the latest betas pretty much covers all that this plugin was created to do...

**Comment by heggink** [comment]
More more than less...

**Comment by moroen** [comment]
@heggink Exactly!
